version: "3"
services:
  web:
    image: alpinejavaswarm:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8081"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
