version: "3"
services:
  web:
    image: alpinejavaswarm:latest
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 200M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  database:
    image: alpineh2database
    # just to expose the console in case we need any testing
    ports: "8082:8082"
    networks: webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    deploy:
      replicas: 0
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
